INSERT INTO public.inventory_items (id, category, nome, quantita, prezzo_unitario, note, sede, tipo, modello, marca, scaffale, ripiano, bancale, grado) VALUES
('SC-001', 'schede', 'ATOMIC', 1, 535, 'LIMENA', 'Limena', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-002', 'schede', '4 IN 1', 1, 600, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-003', 'schede', 'ALADDIN', 1, 450, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-004', 'schede', 'BALLOON', 2, 625, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-005', 'schede', 'BARN', 1, 350, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-006', 'schede', 'BARON', 1, 500, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-007', 'schede', 'BATTLE', 1, 400, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-008', 'schede', 'BEACH', 1, 300, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-009', 'schede', 'BILLION', 1, 850, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-010', 'schede', 'BINGO', 1, 450, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-011', 'schede', 'BOMBER', 1, 500, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-012', 'schede', 'BULL', 1, 600, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-013', 'schede', 'CAMELOT', 1, 500, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-014', 'schede', 'CASH 200', 2, 550, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-015', 'schede', 'CASH 200+', 1, 600, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-016', 'schede', 'CLEOPATRA', 1, 800, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-017', 'schede', 'CRAZY', 1, 900, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-018', 'schede', 'CROWN', 1, 700, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-019', 'schede', 'CIRCUS', 1, 750, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-020', 'schede', 'DOLPHIN', 1, 950, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-021', 'schede', 'DRAGON', 1, 1100, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-022', 'schede', 'EASY', 1, 850, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-023', 'schede', 'EUROPA', 1, 1200, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-024', 'schede', 'FUTURE', 1, 1000, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-025', 'schede', 'GOLD', 1, 1300, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-026', 'schede', 'HIGHWAY', 1, 1050, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-027', 'schede', 'HOTEL', 1, 950, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('SC-028', 'schede', 'KING', 1, 1400, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-001', 'cabinet', 'EARTH NUOVO', 4, 1100, 'carccasas per ricambi', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-002', 'cabinet', 'MIRAGE', 2, 1200, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-003', 'cabinet', 'FLASH', 3, 800, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-004', 'cabinet', 'STAR', 2, 950, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-005', 'cabinet', 'NOVA', 2, 1100, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-006', 'cabinet', 'COSMO', 1, 1300, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-007', 'cabinet', 'ASTRA', 2, 900, '', 'Limena', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-008', 'cabinet', 'LUNA', 1, 850, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-009', 'cabinet', 'ORION', 2, 1000, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-010', 'cabinet', 'TITAN', 1, 1500, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-011', 'cabinet', 'ZEUS', 1, 1400, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-012', 'cabinet', 'HERO', 2, 750, '', 'Magazzino Angelo', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-013', 'cabinet', 'MAXI', 1, 1600, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-014', 'cabinet', 'MEGA', 1, 1800, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-015', 'cabinet', 'ULTRA', 1, 2000, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-016', 'cabinet', 'GIGA', 1, 1700, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-017', 'cabinet', 'POWER', 1, 1100, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-018', 'cabinet', 'ROYAL', 1, 1300, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-019', 'cabinet', 'SUPREME', 1, 1900, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-020', 'cabinet', 'DIAMOND', 1, 2100, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-021', 'cabinet', 'ELITE', 1, 1450, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-022', 'cabinet', 'CLASSIC', 1, 950, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-023', 'cabinet', 'VINTAGE', 1, 850, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-024', 'cabinet', 'PRO', 1, 1250, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CB-025', 'cabinet', 'MASTER', 1, 1850, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CM-001', 'cambiamonete', 'APEX', 7, 2580, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CM-002', 'cambiamonete', 'COMESTERO 7000', 1, 850, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CM-003', 'cambiamonete', 'COMESTERO 8000', 1, 900, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CM-004', 'cambiamonete', 'RAVE', 1, 650, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CM-005', 'cambiamonete', 'SAECO', 1, 550, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CM-006', 'cambiamonete', 'SCIROCCO', 1, 1200, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CM-007', 'cambiamonete', 'CASHFLOW 5700', 1, 700, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CM-008', 'cambiamonete', 'CASHFLOW 6900', 1, 800, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-001', 'accessori', 'STACKER UBA 10 (NO LETTORE)', 167, 80, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-002', 'accessori', 'STACKER UBA 10 CON LETTORE', 10, 120, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-003', 'accessori', 'SCHEDA HDMI', 25, 15, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-004', 'accessori', 'ALIMENTATORE 12V', 15, 25, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-005', 'accessori', 'ALIMENTATORE 24V', 8, 35, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-006', 'accessori', 'LETTORE DI SCHEDE', 20, 45, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-007', 'accessori', 'TASTIERA NUMERICA', 12, 30, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-008', 'accessori', 'SENSORE PROSSIMITA', 30, 12, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-009', 'accessori', 'DISPLAY LCD 16x2', 18, 22, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-010', 'accessori', 'CAVO USB SERIALE', 40, 8, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-011', 'accessori', 'MODULO RELè 4CH', 10, 28, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-012', 'accessori', 'CONVERTITORE RS232', 8, 40, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-013', 'accessori', 'SCHEDA CONTROLLO MOTORE', 5, 150, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('AC-014', 'accessori', 'PULSANTE ILLUMINATO', 50, 6, '', 'Magazzino Principale', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('MN-001', 'monitor', 'PHILIPS 19P4Q', 123, 25, '', 'Magazzino Principale', 'LED19', '19P4Q', 'PHILIPS', 3, 2, 'B', 'A'),
('MN-002', 'monitor', 'PHILIPS V19B', 56, 20, '', 'Magazzino Principale', 'LED19', 'V19B', 'PHILIPS', 3, 1, 'B', 'A'),
('MN-003', 'monitor', 'PHILIPS 9204', 14, 18, '', 'Magazzino Principale', 'LCD19', '9204', 'PHILIPS', 3, 3, 'A', 'B'),
('MN-004', 'monitor', 'PHILIPS V22B', 2, 45, '', 'Magazzino Principale', 'LED22', 'V22B', 'PHILIPS', 3, 4, 'B', 'A'),
('MN-005', 'monitor', 'PHILIPS 19P4', 25, 22, '', 'Magazzino Principale', 'LED19', '19P4', 'PHILIPS', 3, 5, 'A', 'A'),
('MN-006', 'monitor', 'BENQ BL1905', 2, 35, '', 'Magazzino Principale', 'LED19', 'BL1905', 'BENQ', 1, 1, 'A', 'A'),
('MN-007', 'monitor', 'PHILIPS 9204L', 10, 15, '', 'Magazzino Principale', 'LCD 16:10', '9204L', 'PHILIPS', 1, 2, 'B', 'B'),
('MN-008', 'monitor', 'PHILIPS 19P4QB', 14, 20, '', 'Magazzino Principale', 'LED19', '19P4QB', 'PHILIPS', 1, 3, 'B', 'A'),
('MN-009', 'monitor', 'PHILIPS V19', 3, 28, '', 'Magazzino Principale', 'LED19', 'V19', 'PHILIPS', 2, 1, 'B', 'B'),
('MN-010', 'monitor', 'PHILIPS G19', 15, 20, '', 'Magazzino Principale', 'LED19', 'G19', 'PHILIPS', 2, 2, 'A', 'A'),
('MN-011', 'monitor', 'BENQ BL2211', 10, 30, '', 'Magazzino Principale', 'LED 16:10', 'BL2211', 'BENQ', 4, 1, 'A', 'A'),
('MN-012', 'monitor', 'SAMSUNG 24M', 4, 55, '', 'Magazzino Principale', 'LED19', '24M', 'SAMSUNG', 4, 2, 'C', 'A'),
('MN-013', 'monitor', 'SAMSUNG S19B', 6, 40, '', 'Magazzino Principale', 'LED19', 'S19B', 'SAMSUNG', 4, 3, 'C', 'B'),
('MN-014', 'monitor', 'SAMSUNG S22D', 3, 65, '', 'Magazzino Principale', 'LED22', 'S22D', 'SAMSUNG', 4, 4, 'C', 'A'),
('MN-015', 'monitor', 'DELL E1916', 8, 32, '', 'Magazzino Principale', 'LED19', 'E1916', 'DELL', 5, 1, 'A', 'A'),
('MN-016', 'monitor', 'DELL P1917', 5, 38, '', 'Magazzino Principale', 'LED19', 'P1917', 'DELL', 5, 2, 'A', 'A'),
('MN-017', 'monitor', 'DELL P2217', 2, 58, '', 'Magazzino Principale', 'LED22', 'P2217', 'DELL', 5, 3, 'A', 'A'),
('MN-018', 'monitor', 'HP L1940', 11, 20, '', 'Magazzino Principale', 'LCD19', 'L1940', 'HP', 6, 1, 'B', 'B'),
('MN-019', 'monitor', 'LG V197', 7, 25, '', 'Magazzino Principale', 'LED19', 'V197', 'LG', 6, 2, 'B', 'A'),
('MN-020', 'monitor', 'LG 22MP', 2, 60, '', 'Magazzino Principale', 'LED22', '22MP', 'LG', 6, 3, 'C', 'A'),
('MN-021', 'monitor', 'LG V196L', 9, 22, '', 'Magazzino Principale', 'LED19', 'V196L', 'LG', 6, 4, 'B', 'A') ON CONFLICT (id) DO NOTHING;